### ISSUE TITLE
Somewhat opaque build procedure

### ISSUE THREAD

**Issue by chrismamo1** [mirage/ocaml-cow#83] opened 2015-08-13 18:58 UTC
In working on a patch ([PR#82](https://github.com/mirage/ocaml-cow/pull/82)) I have run into strange compilation problems involving this error message:

    Circular build detected (lib/cow.cmi already seen in [ lib/html.cmo; lib/cow.cmi; cow.all ])

I tried to investigate further, but a cursory examination of the `Makefile` shows that all of the actual compilation for OCaml-COW is done by the mysterious `cmd` executable which is already included in the repository. Is this something worth fixing? Is it even broken?

**Comment by samoht** [comment] 2015-08-15 11:10
The build procedure is very complex because the library is using the syntax extension which uses the library. The only sane way to fix this would be to:

- have stand-alone libraries (for css/html/xml/json) which does not use the syntax extensions at all
- build the syntax extensions as a shim on top of the library

It's something that I've been wanting for a long time but didn't find the time to do it properly. Would be great if you could do it properly :-)

**Comment by dsheets** [comment] 2015-08-17 10:48
I believe the problem is [here](https://github.com/mirage/ocaml-cow/pull/82/files#diff-e228a59086faa3f105e0d6fbbe902ad9R230). `Html` is packed in `Cow` and so probably shouldn't reference `Cow`. I don't think this error case has anything to do with the complexity of the build system.

**Comment by samoht** [comment] 2015-08-17 11:20
> I don't think this error case has anything to do with the complexity of the build system.

agree, but this build system is really horrible and should disappear :-)

**Comment by samoht** [comment] 2016-03-13 21:34
This is now fixed, no more syntax extension in cow 2.0

**Closed by samoht** 2016-03-13 21:34 UTC
